FROM ghcr.io/cyber-dojo-languages/go:b7e7991
LABEL maintainer=jon@jaggersoft.com

COPY ./install.sh .
RUN ./install.sh && rm ./install.sh

#ENV GO111MODULE=auto
#RUN go get github.com/smartystreets/goconvey/convey
